---
  - name: "Update VPS"
    shell: apt update
  
  - name: "Install package"
    apt: 
      name: '{{ item }}'
    with_items: 
      - software-properties-common
      - python3
      - python3-setuptools
      - python3-dev
      - build-essential
      - python3-pip
      - python3-mysqldb